# Generated by Django 6.0.2 on 2026-02-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heatmap_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessuser',
            name='recommended_business',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
